<?php
require_once('classes/config.php');
require_once('classes/lang.php');


$lang = isset($_COOKIE["lang"]) ? $_COOKIE["lang"] : "ES";

define("NAV_HOME", lang::getTranslation($lang, "NAV_HOME"));
define("NAV_GALLERY", lang::getTranslation($lang, "NAV_GALLERY"));
define("NAV_CONTACT", lang::getTranslation($lang, "NAV_CONTACT"));
define("NAV_DOWNLOADS", lang::getTranslation($lang, "NAV_DOWNLOADS"));
define("NAV_SESSION_CLOSE", lang::getTranslation($lang, "NAV_SESSION_CLOSE"));
define("MAIN_HERO", lang::getTranslation($lang, "MAIN_HERO"));
define("BODY_TERMS", lang::getTranslation($lang, "BODY_TERMS"));
define("MENU_LANG", lang::getTranslation($lang, "MENU_LANG"));
define("USER_IMAGES", lang::getTranslation($lang, "USER_IMAGES"));
define("USER_INFO", lang::getTranslation($lang, "USER_INFO"));
define("GALLERY_BY", lang::getTranslation($lang, "GALLERY_BY"));
define("GALLERY_UPLOAD_IMAGE", lang::getTranslation($lang, "GALLERY_UPLOAD_IMAGE"));
define("GALLERY_UPLOAD", lang::getTranslation($lang, "GALLERY_UPLOAD"));
define("GALLERY_TITLE", lang::getTranslation($lang, "GALLERY_TITLE"));
define("GALLERY_IMAGE", lang::getTranslation($lang, "GALLERY_IMAGE"));
define("DATA_USER", lang::getTranslation($lang, "DATA_USER"));
define("DATA_PERSONAL", lang::getTranslation($lang, "DATA_PERSONAL"));
define("DATA_NAME", lang::getTranslation($lang, "DATA_NAME"));
define("DATA_LASTNAME", lang::getTranslation($lang, "DATA_LASTNAME"));
define("DATA_EMAIL", lang::getTranslation($lang, "DATA_EMAIL"));
define("DATA_CREATED", lang::getTranslation($lang, "DATA_CREATED"));
define("DATA_ACTION", lang::getTranslation($lang, "DATA_ACTION"));
define("DATA_IMAGE", lang::getTranslation($lang, "DATA_IMAGE"));
define("DATA_AVAILABLE", lang::getTranslation($lang, "DATA_AVAILABLE"));
define("DATA_LOGTIME", lang::getTranslation($lang, "DATA_LOGTIME"));
define("DATA_VERIFY", lang::getTranslation($lang, "DATA_VERIFY"));
define("DATA_OLDPASS", lang::getTranslation($lang, "DATA_OLDPASS"));
define("CONTACT_SUBJECT", lang::getTranslation($lang, "CONTACT_SUBJECT"));
define("LOG_PASSWORD", lang::getTranslation($lang, "LOG_PASSWORD"));
define("LOG_REPPASSWORD", lang::getTranslation($lang, "LOG_REPPASSWORD"));
define("ACTION_EDIT", lang::getTranslation($lang, "ACTION_EDIT"));
define("DATA_CHANGEPASSWORD", lang::getTranslation($lang, "DATA_CHANGEPASSWORD"));
define("UPLOAD_SUCCESS", lang::getTranslation($lang, "UPLOAD_SUCCESS"));
define("UPLOAD_EXISTS", lang::getTranslation($lang, "UPLOAD_EXISTS"));
define("UPLOAD_SIZE_ERROR", lang::getTranslation($lang, "UPLOAD_SIZE_ERROR"));
define("MAIN_1", lang::getTranslation($lang, "MAIN_1"));
define("MAIN_2", lang::getTranslation($lang, "MAIN_2"));
define("MAIN_3", lang::getTranslation($lang, "MAIN_3"));
define("MAIN_4", lang::getTranslation($lang, "MAIN_4"));
define("MAIN_5", lang::getTranslation($lang, "MAIN_5"));
define("MAIN_6", lang::getTranslation($lang, "MAIN_6"));
define("MAIN_7", lang::getTranslation($lang, "MAIN_7"));
define("MAIN_8", lang::getTranslation($lang, "MAIN_8"));
define("MAIN_9", lang::getTranslation($lang, "MAIN_9"));
define("MAIN_PROJECTS", lang::getTranslation($lang, "MAIN_PROJECTS"));